name: moriEspanso
parent: default

matches:
  - trigger: ":usq"
    replace: "University of Southern Queensland"
  - trigger: ":unisig"
    replace: |
              Thanks,

              Mitch Drake
              Digital Learning Technician
              Office for the Advancement of Learning and Teaching (OALT) | Y265
              T: +61 7 4631 2018
              E: Mitch.Drake@usq.edu.au
              University of Southern Queensland | Toowoomba
              Queensland | 4350 | Australia
  - trigger: ":newcontact?"
    replace: "I'm not sure if you're the right person to contact for this, but $|$. If this isn't your domain, or someone else would be better suited to help, please let me know. \nThanks so much for your time," 
